"""init schema

Revision ID: bd7e6a8605e2
Revises:
Create Date: 2025-10-21 21:26:28.419481

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7e6a8605e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activity',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            'level >= 1 AND level <= 3',
            name=op.f('ck_activity_level_between_1_3'),
        ),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['activity.id'],
            name=op.f('fk_activity_parent_id_activity'),
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_activity')),
    )
    op.create_index(
        op.f('ix_activity_name'), 'activity', ['name'], unique=False
    )
    op.create_index(
        op.f('ix_activity_parent_id'), 'activity', ['parent_id'], unique=False
    )
    op.create_table(
        'building',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column(
            'latitude', sa.Numeric(precision=10, scale=7), nullable=False
        ),
        sa.Column(
            'longitude', sa.Numeric(precision=10, scale=7), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_building')),
        sa.UniqueConstraint('address', name='uq_building_address'),
    )
    op.create_index(
        op.f('ix_building_address'), 'building', ['address'], unique=True
    )
    op.create_index(
        'ix_building_lat_lon',
        'building',
        ['latitude', 'longitude'],
        unique=False,
    )
    op.create_index(
        op.f('ix_building_latitude'), 'building', ['latitude'], unique=False
    )
    op.create_index(
        op.f('ix_building_longitude'), 'building', ['longitude'], unique=False
    )
    op.create_table(
        'organization',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('building_id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['building_id'],
            ['building.id'],
            name=op.f('fk_organization_building_id_building'),
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    )
    op.create_index(
        op.f('ix_organization_building_id'),
        'organization',
        ['building_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organization_name'), 'organization', ['name'], unique=False
    )
    op.create_table(
        'organization_activities',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['activity_id'],
            ['activity.id'],
            name=op.f('fk_organization_activities_activity_id_activity'),
            ondelete='RESTRICT',
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
            name=op.f(
                'fk_organization_activities_organization_id_organization'
            ),
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint(
            'organization_id',
            'activity_id',
            name=op.f('pk_organization_activities'),
        ),
    )
    op.create_table(
        'organizationphone',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('phone_number', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
            name=op.f('fk_organizationphone_organization_id_organization'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_organizationphone')),
        sa.UniqueConstraint('phone_number', name='uq_org_phone_phone_number'),
    )
    op.create_index(
        op.f('ix_organizationphone_organization_id'),
        'organizationphone',
        ['organization_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organizationphone_phone_number'),
        'organizationphone',
        ['phone_number'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_organizationphone_phone_number'),
        table_name='organizationphone',
    )
    op.drop_index(
        op.f('ix_organizationphone_organization_id'),
        table_name='organizationphone',
    )
    op.drop_table('organizationphone')
    op.drop_table('organization_activities')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(
        op.f('ix_organization_building_id'), table_name='organization'
    )
    op.drop_table('organization')
    op.drop_index(op.f('ix_building_longitude'), table_name='building')
    op.drop_index(op.f('ix_building_latitude'), table_name='building')
    op.drop_index('ix_building_lat_lon', table_name='building')
    op.drop_index(op.f('ix_building_address'), table_name='building')
    op.drop_table('building')
    op.drop_index(op.f('ix_activity_parent_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_name'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
